run_mode: debug
addr: :80
name: lj-go-practice
url: http://127.0.0.1
max_ping_count: 10

logger:
  writers: file,stdout
  logger_level: INFO
  logger_file: logs/lj-go-practice
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 20
  log_backup_count: 7

db:
  schema: demo
  host: 127.0.0.1
  port: 3306
  username: root
  password: root123456

redis:
  host: 127.0.0.1:6379
  index: 0
  pool_size: 10
  password: 123456
